name: ubuntu20-docker-build

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ubuntu-20-dev

jobs:

  ubuntu-20-dev:
    runs-on: [self-hosted, linux]
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Setup JArtifactory
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}

      - name: Build image
        run: |
          echo "${{ secrets.JF_TOKEN }}" | docker login eflutter.jfrog.io -u ${{ secrets.JF_USER }} --password-stdin

          docker buildx install
          echo "*** docker build start ***"
          IMAGE_ID=eflutter.jfrog.io/containers-docker/$IMAGE_NAME
          docker build --platform=linux/amd64 --tag=$IMAGE_ID -f=ubuntu-20-dev/Dockerfile --metadata-file=build-metadata --push .
          echo "*** docker build end ***"
          jf rt ping
          jf c add eflutter
          echo "*** build-docker-create start ***"
          jf rt build-docker-create containers-docker --server-id=eflutter --image-file build-metadata --build-name ${GITHUB_JOB} --build-number ${GITHUB_RUN_ID}
          echo "*** build-docker-create end ***"
          echo "*** build-publish start ***"
          jf rt build-publish --server-id=eflutter  ${GITHUB_JOB} ${GITHUB_RUN_ID}
          echo "*** build-publish end ***"
          docker buildx uninstall
